FROM node as build

ADD . /frontend

WORKDIR /frontend

RUN npm config set registry https://registry.npm.taobao.org

RUN npm install

RUN npm run build

FROM nginx:alpine

COPY --from=build /frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /frontend/dist /usr/share/nginx/html
