stages:
    - build-vue
    - build-gin
    - deploy

job1:
    stage: build-vue
    tags:
        - basic
    script:
        - cd vue
        - docker build -t registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-vue:v1.0.0 .
        - docker push registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-vue:v1.0.0
    only:
        - master

job2:
    stage: build-gin
    tags:
        - basic
    script:
        - cd singo
        - docker build -t registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-api:v1.0.0 .
        - docker push registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-api:v1.0.0
    only:
        - master
        
job3:
    stage: deploy
    tags:
        - basic
    script:
        - echo "I am in deploy stage"
    only:
        - master
