stages:
    - build
    - test
    - deploy

job1:
    stage: build
    tags:
        - basic
    script:
        - pwd
        - echo "I am in build stage"
    only:
        - master
        
job2:
    stage: test
    tags:
        - basic
    script:
        - echo "I am job2">>1.txt
        - echo "I am in test stage"
    only:
        - master
        
job3:
    stage: deploy
    tags:
        - basic
    script:
        - echo "I am job3"
        - echo "I am in deploy stage"
    only:
        - master