stages:
    - build
    - test
    - deploy

job1:
    stage: build
    tags:
        - alpha
    script:
        - ls
        - echo "I am job1"
        - echo "I am in build stage"
        
job2:
    stage: test
    tags:
        - alpha
    script:
        - touch 1.txt
        - echo "I am job2"
        - echo "I am in test stage"
        
job3:
    stage: deploy
    tags:
        - alpha
    script:
        - touch 2.txt
        - echo "I am job3"
        - echo "I am in deploy stage"