stages:
    - build-vue
    - build-gin
    - deploy

job1:
    stage: build-vue
    tags:
        - basic
    script:
        - cd vue
        - docker login -u "yfgooo" -p "$CI_REGISTRY_PASSWORD" registry.cn-hangzhou.aliyuncs.com
        - echo $CI_COMMIT_TAG
        - docker build -t registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-vue:$CI_COMMIT_TAG .
        - docker push registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-vue:$CI_COMMIT_TAG
    only:
        - tags

job2:
    stage: build-gin
    tags:
        - basic
    script:
        - cd singo
        - docker login -u "yfgooo" -p "$CI_REGISTRY_PASSWORD" registry.cn-hangzhou.aliyuncs.com
        - echo $CI_COMMIT_TAG
        - docker build -t registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-api:$CI_COMMIT_TAG .
        - docker push registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-api:$CI_COMMIT_TAG
    only:
        - tags
        
job3:
    stage: deploy
    tags:
        - basic
    script:
        - echo "I am in deploy stage"
    only:
        - master
