version: "3"
# 管理的服务
services:
  redis:
    # 指定镜像
    image: redis:4
    restart: always
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - "./data/redis/conf:/usr/local/etc/redis"
      - "./data/redis/data:/data"
    command:
      # 执行的命令
      redis-server
 
  mysql:
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./data/mysql/data:/var/lib/mysql"
      - "./data/mysql/conf.d:/etc/mysql/conf.d"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_blog
