version: '2'
services:
  vue:
    image: registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-vue:v1.0.3
    restart: always
    ports:
      - 3001:80
      
  blog-api:
    image: registry.cn-hangzhou.aliyuncs.com/yfgooo/blog-api:v1.0.3
    container_name: blog-api
    restart: always
    environment:
      MYSQL_DSN: "root:root@tcp(mysql:3306)/go_blog?charset=utf8&parseTime=True&loc=Local"
      REDIS_ADDR: "redis:6379"
      REDIS_DB: "0"
      SESSION_SECRET: "rBaXcdwoorC1"
      GIN_MODE: "release"
      IMAGE_STORE: "./static/"
      IMAGE_URL: "/static/"
    ports:
      - 3002:3000
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:5.6
    command: [
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--default-time-zone=+8:00'
        ]
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./data/mysql/data:/var/lib/mysql"
      - "./data/mysql/conf.d:/etc/mysql/conf.d"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_blog

  redis:
    image: redis:4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - "./data/redis/conf:/usr/local/etc/redis"
      - "./data/redis/data:/data"
    command:
      redis-server